routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@logout']);
Route::get('/home', 'HomeController@index');
Route::get('state/{country}/search', 'Adm\Location\StateController@getStates');
Route::get('city/{state}/search', 'Adm\Location\CityController@getCities');

Route::group(['namespace' => 'Site'], function () {
    Route::group(['middleware' => 'statusapp'], function () {
        Route::get('/', ['as' => 'index', 'uses' => 'Index\IndexController@index']);
        ROute::get('/css/callCss', ['as' => 'callCss', 'uses' => 'App\AppController@callCss']);
        Route::get('/politics', function(){
            return view('site.politics.index');
        });
        Route::get('/conditions', function(){
            return view('site.conditions.index');
        });
        Route::get('/resources/{resource}', ['as' => 'resource', 'uses' => 'Resources\ResourceController@view']);
        Route::get('/aboutus', ['as' => 'aboutus', 'uses' => 'AboutUs\AboutUsController@index']);
        Route::get('/products', ['as' => 'products', 'uses' => 'Products\ProductsController@index']);
        Route::get('/products/ver/{product}', ['as' => 'products.view', 'uses' => 'Products\ProductsController@view']);
        Route::post('/leave', ['as' => 'leave', 'uses' => 'Contact\ContactController@leave']);
        Route::get('/contact', ['as' => 'contact', 'uses' => 'Contact\ContactController@index']);
        Route::post('contact/{contact}', ['as' => 'contact.send', 'uses' => 'Contact\ContactController@sendMessage']);
        Route::get('/articles', ['as' => 'articles', 'uses' => 'Articles\ArticleController@index']);
        Route::get('article/ver/{article}', ['as' => 'article.view', 'uses' => 'Articles\ArticleController@view']);
        Route::post('article/comment', ['as' => 'article.comment', 'uses' => 'Articles\ArticleController@comment']);
        Route::get('/galleries', ['as' => 'galleries', 'uses' => 'Galleries\GalleriesController@index']);
        Route::get('galleries/ver/{gallery}', ['as' => 'galleries.view', 'uses' => 'Galleries\GalleriesController@view']);
        Route::get('/distribution', ['as' => 'distribution', 'uses' => 'Distribution\DistributionController@index']);
        Route::get('/cart', ['as' => 'cart', 'uses' => 'Cart\CartController@index']);
        Route::post('cart/add', ['as' => 'addcart', 'uses' => 'Cart\CartController@addCart']);
        Route::post('cart/del', ['as' => 'delcart', 'uses' => 'Cart\CartController@delCart']);
        Route::post('cart/change', ['as' => 'chcart', 'uses' => 'Cart\CartController@changeCart']);
        Route::post('/confirm_stock', ['as' => 'confirmcart', 'uses' => 'Cart\CartController@confirm']);
        Route::post('coupon/apply', ['as' => 'appCoupon', 'uses' => 'Cart\CheckoutController@apCoupon']);
        Route::get('/checkout', ['as' => 'checkout', 'uses' => 'Cart\CheckoutController@index']);
        Route::post('/tarifa-envio', ['as'=>'priceship', 'uses'=>'Cart\CheckoutController@calculateShip']);
        Route::post('/comprar', ['as' => 'cart.checkout', 'uses' => 'Cart\CheckoutController@checkOut']);
        /*********************** LOGIN ****************************/
        Route::post('/iniciar', ['as' => 'authlogin', 'uses' => 'Auth\AuthController@doLogin']);
        Route::post('/restaurar', ['as' => 'recovery', 'uses' => 'Auth\AuthController@loginRecovery']);
        Route::get('/cerrar-sesion', ['as' => 'userlogout', 'uses' => 'Auth\AuthController@logout']);
        Route::post('/registro', ['as' => 'register.data', 'uses' => 'Auth\AuthController@registerData']);
        /*********************** /LOGIN ****************************/

        Route::group(['middleware' => 'auth'], function () {
            /********************Account**********************/
            Route::get('/mi-cuenta', ['as' => 'myaccount', 'uses' => 'User\UserController@myAccount']);
            Route::post('/actualizar-datos', ['as' => 'updateaccount', 'uses' => 'User\UserController@update']);
            Route::get('/imagen', ['as' => 'imageprofile', 'uses' => 'User\UserController@image']);
            Route::post('/actualizar-imagen', ['as' => 'imageprofile.data', 'uses' => 'User\UserController@updateImage']);
            Route::get('/mi-contrasena', ['as' => 'changepassword', 'uses' => 'User\UserController@changePassword']);
            Route::post('/cambiar-contrasena', ['as' => 'changepass', 'uses' => 'User\UserController@updatePassword']);
            Route::get('/mi-direccion', ['as' => 'useraddress', 'uses' => 'User\UserController@userAddress']);
            Route::post('/borrar-direccion/{address}', ['as' => 'deleteaddress', 'uses' => 'User\UserController@deleteAddress']);
            Route::post('/cambiar-direccion/{address}', ['as' => 'changeaddress', 'uses' => 'User\UserController@changeAddress']);
            Route::post('/cerrar-cuenta', ['as' => 'deleteuser', 'uses' => 'User\UserController@deleteUser']);

            Route::get('/mis-ordenes', ['as' => 'userorders', 'uses' => 'User\UserController@userOrders']);
            Route::get('/ver-orden/{order}', ['as' => 'vieworder', 'uses' => 'User\UserController@viewOrder']);
            Route::get('/imprimir-orden/{order}', ['as' => 'printorder', 'uses' => 'User\UserController@printOrder']);
            /******************End Account********************/
        });
        Route::get('/respuesta-de-pago', ['as' => 'payment.response', 'uses' => 'Payment\PaymentController@paymentResponse']);
        Route::get('/imprimir-recibo/{invoice}', ['as' => 'payment.print', 'uses' => 'Payment\PaymentController@printInvoice']);

    });
});


Route::get('/adm', function () {
    return redirect('/login');
});

Route::group(['prefix' => 'adm'], function () {
    Route::auth();
    Route::group(['middleware' => ['auth','admin']], function () {

            Route::group(['namespace' => 'Adm'], function () {

                Route::group(['middleware' => ['auth','superadmin']], function () {
                    Route::resource('admin', 'Admin\AdminController', ['as' => 'adm']);
                    Route::get('app', ['as' => 'adm.app.configure', 'uses' => 'App\AppController@configure']);
                    Route::post('app', ['as' => 'adm.app.update', 'uses' => 'App\AppController@update']);
                    /********************PayU**********************/
                    Route::get('payu', ['as' => 'adm.payu.index', 'uses' => 'PayU\PayuController@index']);
                    Route::post('payu/update', ['as' => 'adm.payu.update', 'uses' => 'PayU\PayuController@update']);
                    /******************End PayU********************/
                    /********************Invoice**********************/
                    Route::get('invoice', ['as' => 'adm.invoice.index', 'uses' => 'Invoice\InvoiceController@index']);
                    Route::get('invoice/{invoice}', ['as' => 'adm.invoice.show', 'uses' => 'Invoice\InvoiceController@show']);
                    Route::post('invoice/{invoice}/null', ['as' => 'adm.invoice.null', 'uses' => 'Invoice\InvoiceController@invalidate']);
                    Route::post('invoice/{invoice}/send', ['as' => 'adm.invoice.send', 'uses' => 'Invoice\InvoiceController@track']);
                    Route::get('invoice/{invoice}/print', ['as' => 'adm.invoice.print', 'uses' => 'Invoice\InvoiceController@printInvoice']);
                    /******************End Invoice********************/
                });
                Route::get('home', 'Dashboard\DashboardController@index');
                Route::get('dashboard',['as' => 'adm.dashboard', 'uses' => 'Dashboard\DashboardController@index']);
                Route::resource('menu', 'Menu\MenuController', ['as' => 'adm']);
                Route::get('footer',['as' => 'adm.footer', 'uses' => 'Footer\FooterController@index']);
                Route::post('footer/update', ['as' => 'adm.footer.update', 'uses' => 'Footer\FooterController@update']);
                Route::resource('resources', 'Resources\ResourceController', ['as' => 'adm']);
                Route::resource('distribution', 'Distribution\DistributionController', ['as' => 'adm']);
                Route::resource('modals', 'Modals\ModalsController', ['as' => 'adm']);
                Route::post('modals/status', ['as' => 'adm.modals.status', 'uses' => 'Modals\ModalsController@status']);
                /********************** Home **************************/
                Route::get('header',['as' => 'adm.header', 'uses' => 'Header\HeaderController@index']);
                Route::post('header/update', ['as' => 'adm.header.update', 'uses' => 'Header\HeaderController@update']);
                Route::get('header/images', ['as' => 'adm.header.images', 'uses' => 'Header\HeaderController@images']);
                Route::post('header/links', ['as' => 'adm.headerlink', 'uses' => 'Header\HeaderController@links']);
                Route::post('header/{image}/upload', ['as' => 'adm.headerimage.upload', 'uses' => 'Header\HeaderController@upload']);
                Route::post('header/{image}/delImage', ['as' => 'adm.headerimage.destroy', 'uses' => 'Header\HeaderController@destroyImage']);
                /******************* End Home *************************/
                /***********************AboutUs************************/
                Route::get('aboutus',['as' => 'adm.aboutus', 'uses' => 'AboutUs\AboutUsController@index']);
                Route::post('aboutus/update', ['as' => 'adm.aboutus.update', 'uses' => 'AboutUs\AboutUsController@update']);

app/Http/Controllers/Adm/AboutUs/AboutUsController.php
<?php

namespace App\Http\Controllers\Adm\AboutUs;

use App\Http\Controllers\Controller;

use App\Http\Requests\Adm\AboutUs\UpdateAboutUsRequest;
use App\Model\AboutUs\AboutUs;
use Exception;
use Folklore\Image\Facades\Image;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;


class AboutUsController extends Controller
{
    protected $dir;
    protected $url;

    public function __construct()
    {
        $this->dir = appData()->dirdata . '/images/aboutus/';
        $this->url = appData()->urldata . '/images/aboutus/';
    }

    public function index()
    {
        $data = AboutUs::find(1);
        if(!$data){
            $data = (object)[];
            $data->id = 1;
            $data->text = '';
        }
        return view('adm.aboutus.edit', compact('data'));
    }

    public function update(UpdateAboutUsRequest $request)
    {
        DB::beginTransaction();
        try {
            $data = AboutUs::find(1);
            if(!$data){
                $data = new AboutUs();
            }
            $data->id = 1;
            $data->text = $request->get('ta_text');

            if ($request->file('fl_image')) {
                $image = md5(time()) . '.png';
                $imgProduct = $request->file('fl_image');
                $dirImg = $this->dir . $image;
                Image::make($imgProduct, ['width' => 600, 'height' => 600, 'greyscale' => false])->save($dirImg);
                if (File::exists($this->dir . $data->image)) {
                    File::delete($this->dir . $data->image);
                }
                $data->image = $image;
            }
            $data->save();
            DB::commit();
            if ($request->ajax()) {
                return response()->json([
                    'message' => trans('app.edit_success')
                ]);
            }
        } catch (Exception $e) {
            DB::rollback();
            //dd($e->getMessage(),$e->getFile(),$e->getLine());
            if ($request->ajax()) {
                return response()->json([
                    'error' => trans('app.edit_problem')
                ]);
            }
        }
    }

}

app/Http/Controllers/Adm/App/AppController.php
<?php

namespace App\Http\Controllers\Adm\App;


use App\Http\Controllers\Controller;
use App\Http\Requests\Adm\App\UpdateAppRequest;
use App\Model\App\App;
use App\Model\App\Currency;
use Exception;
use Folklore\Image\Facades\Image;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

class AppController extends Controller
{

    protected $dir;
    protected $url;

    public function __construct()
    {
        $this->dir = appData()->dirdata . '/images/app/';
        $this->url = appData()->urldata . '/images/app/';
    }

    public static function appData()
    {
        return App::with('currency')->firstOrFail();
    }

    public function configure()
    {
        $data = App::firstOrFail();
        $data->directory = env('DOCUMENT_ROOT');
        $data->currencyList = Currency::selection();
        return view('adm.app.index', compact('data'));
    }

    public function update(UpdateAppRequest $request)
    {
        $data = App::firstOrFail();
        DB::beginTransaction();
        try {
            $data->color = $request->get('tx_color');
            $data->name = $request->get('tx_name');
            $data->email = $request->get('tx_email');
            $data->phone = $request->get('tx_phone');
            $data->cellphone = $request->get('tx_mobile');
            $data->address = $request->get('tx_address');
            $data->website = $request->get('tx_website');
            $data->dirdata = $request->get('tx_dir');
            $data->urldata = $request->get('tx_url');
            $data->copyright = $request->get('tx_copyright');
            $data->id_currency = $request->get('sl_currency');
            $data->tax_value = $request->get('tx_tax');
            $data->min_value = $request->get('tx_min_value');
            if ($request->file('fn_file')) {
                $image = md5(time()) . '.png';
                $imgProduct = $request->file('fn_file');
                $dirImg = $this->dir . $image;
                Image::make($imgProduct, ['width' => 178, 'height' => 57, 'greyscale' => false])->save($dirImg);

                if (File::exists($this->dir . $data->logo)) {
                    File::delete($this->dir . $data->logo);
                }
                $data->logo = $image;
            }
            $data->name_boucher = $request->get('tx_name_boucher');
            $data->email_boucher = $request->get('tx_email_boucher');
            $data->phone_boucher = $request->get('tx_phone_boucher');
            $data->address_boucher = $request->get('tx_address_boucher');
            $data->website_boucher = $request->get('tx_website_boucher');
            $data->save();
            DB::commit();
            if ($request->ajax()) {
                return response()->json([
                    'message' => trans('app.edit_success')
                ]);
            }
        } catch (Exception $e) {
            DB::rollback();
            //dd($e->getMessage(),$e->getFile(),$e->getLine());
            if ($request->ajax()) {
                return response()->json([
                    'error' => trans('app.edit_problem')
                ]);
            }
        }
    }
}

app/Http/Controllers/Adm/App/AppSocialController.php
<?php

namespace App\Http\Controllers\Adm\App;

use App\Http\Controllers\Controller;
use App\Http\Requests\Adm\AppSocial\AppSocialRequest;
use App\Http\Requests\Adm\AppSocial\AppaboutusRequest;
use App\Model\Social\AppSocial;
use App\Model\Social\Social;
use Exception;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\DB;

class AppSocialController extends Controller
{
    public function addSocial()
    {
        $data = (object)[];
        $data->appsocial = AppSocial::with('social')->get();
        $data->socialList = Social::selection();
        return view('adm.appsocial.edit', compact('data'));
    }

    public function fields($cont)
    {
        $data = (object)[];
        $data->cont = $cont;
        $data->socialList = Social::selection();
        return (string)view('adm.appsocial.fields', compact('data'));
    }

    public function update(AppSocialRequest $request)
    {

        DB::beginTransaction();
        try {
            AppSocial::deleteSocial(appData()->id);

            if ($request->get('sl_social')) {
                foreach ($request->get('sl_social') as $key => $val) {
                    $social = new AppSocial();
                    $social->id_app = appData()->id;
                    $social->id_social = $request->get('sl_social')[$key];
                    $social->link = $request->get('tx_link')[$key];
                    $social->save();
                }
            }
            DB::commit();
            if ($request->ajax()) {
                return response()->json([
                    'message' => trans('app.edit_success')
                ]);
            }
        } catch (Exception $e) {
            DB::rollback();
            //dd($e);
            if ($request->ajax()) {
                return response()->json([
                    'error' => trans('app.edit_problem')
                ]);
            }
        }
    }
}

resources/views/adm/distribution/index.blade.php
@extends('adm.layouts.page')

@section('title')
    {!! trans('app.distribution') !!}
@endsection
@section('content')
    @include('adm.layouts.msgmodal')
    <div class="modal fade trash-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                {!! Form::open(['route'=>['adm.distribution.destroy','IDX'],'method'=>'DELETE','name'=>'frmDes','id'=>'frmDes','role'=>'form']) !!}
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{!! trans('app.message_alert') !!}</h4>
                </div>
                <div class="modal-body">
                    {!! Form::hidden('hd_trash',null,['id'=>'hd_trash']) !!}
                    <p>{!! trans('app.want_delete') !!}</p>
                </div>
                <div class="modal-footer">
                    {!! Form::button(trans('app.cancel'),['name'=>'bt_cancel','id'=>'bt_cancel','class'=>'btn btn-default','data-dismiss'=>'modal']) !!}
                    {!! Form::button(trans('app.accept'),['name'=>'bt_trash','id'=>'bt_trash','class'=>'btn btn-danger','data-dismiss'=>'modal']) !!}
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

    <div class="content-wrapper">
        @section('here') {!! trans('app.distribution') !!}@endsection
        @section('breadcumb')
            <li>{!! trans('app.distribution') !!}</li>
        @endsection
        @include('adm.layouts.bread')
        <section class="content">

            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">
                                {!! trans('pagination.currentPage') !!}
                                <span class="badge bg-primary">{!! $list->currentPage() !!}</span>
                                {!! trans('pagination.lastPage') !!}
                                <span class="badge bg-primary">{!! $list->lastPage() !!}</span>
                            </h3>
                            <div class="box-tools">
                                {!! Form::model(Request::only(['buscar']), ['route'=>'adm.distribution.index', 'style'=>'width: 150px;', 'method'=>'GET', 'rol'=>'search']) !!}
                                <div class="input-group">
                                    {!! Form::text('search',$list->search,['class'=>'form-control input-sm pull-right', 'placeholder'=>''.trans("ph.search").'']) !!}
                                    <div class="input-group-btn">
                                        {!! Form::button('<i class="fa fa-search"></i>',['class'=>'btn btn-sm btn-default','role'=>'button','type'=>'submit']) !!}
                                    </div>
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                        <div class="box-body table-responsive no-padding">
                            @if($list->isEmpty())
                                <div class="box-body">{!! trans('app.no_result') !!}</div>
                            @else
                                <table class="table table-hover">
                                    <tbody>
                                    <tr>
                                        <th>{!! trans('app.number') !!}</th>
                                        <th>{!! trans('app.id') !!}</th>
                                        <th>{!! trans('distribution.name') !!}</th>
                                        <th>{!! trans('distribution.city') !!}</th>
                                        <th>{!! trans('app.actions') !!}</th>
                                    </tr>
                                    @php $count=1 @endphp
                                    @foreach($list as $for)
                                        <tr class="target-{!! $for->id !!}">
                                            <td>{!! $loop->iteration !!}</td>
                                            <td>{!! $for->id !!}</td>
                                            <td>{!! $for->name !!} </td>
                                            <td>{!! (!is_null($for->id_city))? $for->city->name : '' !!} </td>
                                            <td>
                                                {!! html_entity_decode(link_to_route('adm.distribution.edit','<span class="label label-info"><i class="fa fa-pencil"></i></span>',['id'=>$for->id],['data-toggle'=>'tooltip','data-placement'=>'left','title'=>trans('app.edit_info')])) !!}
                                                <span class="label label-danger span-link trash-data"
                                                      trash="{!! $for->id !!}" data-toggle="tooltip"
                                                      data-placement="left"
                                                      title="{!! trans('app.delete_info') !!}">
                                                      <i class="fa fa-trash"></i>
                                                </span>

                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @endif
                        </div>
                        <div class="box-footer clearfix">
                            <div class="panel-body pull-right">
                                <span class="badge bg-success">{!! $list->count() !!}</span>
                                {!! trans('pagination.count') !!}
                                <span class="badge bg-success">{!! $list->total() !!}</span>
                            </div>

                            {!! $list->appends(Request::only(['search']))->render() !!}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="add-data">
        {!! html_entity_decode(link_to_route('adm.distribution.create','<i class="fa fa-plus"></i> '.trans('app.register'),null,['class'=>'btn btn-app bg-aqua'])) !!}
    </div>
@endsection
@section('jsBottom')
    {!! Html::script('cms/dist/js/messages.js') !!}
    {!! Html::script('cms/dist/js/app/distribution/index.js') !!}
@endsection